# Generated by Django 5.2.4 on 2025-08-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pendingsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingsignup",
            name="username",
            field=models.CharField(max_length=255),
        ),
    ]
