# Generated by Django 5.2.4 on 2025-08-07 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_pendingsignup_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingsignup",
            name="password",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
