# Generated by Django 5.2.4 on 2025-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_customuser_is_active_customuser_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pendingsignup",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
