# Generated by Django 5.2.4 on 2025-08-10 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_is_active_alter_pendingsignup_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("minutes_inbound_limit", models.PositiveIntegerField(default=0)),
                ("minutes_outbound_limit", models.PositiveIntegerField(default=0)),
                ("minutes_total_limit", models.PositiveIntegerField(default=0)),
                ("agents_allowed", models.PositiveIntegerField(default=1)),
                ("analytics_access", models.BooleanField(default=False)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                ("minutes_used_inbound", models.PositiveIntegerField(default=0)),
                ("minutes_used_outbound", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="accounts.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="accounts_su_is_acti_201128_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="accounts_su_start_d_6ed817_idx"
                    ),
                ],
            },
        ),
    ]
